/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LocaleIndexImport } from './routes/$locale.index'
import { Route as LocaleBoardImport } from './routes/$locale.$board'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleIndexRoute = LocaleIndexImport.update({
  path: '/$locale/',
  getParentRoute: () => rootRoute,
} as any)

const LocaleBoardRoute = LocaleBoardImport.update({
  path: '/$locale/$board',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$locale/$board': {
      id: '/$locale/$board'
      path: '/$locale/$board'
      fullPath: '/$locale/$board'
      preLoaderRoute: typeof LocaleBoardImport
      parentRoute: typeof rootRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LocaleBoardRoute,
  LocaleIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$locale/$board",
        "/$locale/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$locale/$board": {
      "filePath": "$locale.$board.tsx"
    },
    "/$locale/": {
      "filePath": "$locale.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
